### PR TITLE
bump bulma version to 0.7.5

### PR DESCRIPTION
**Pull request by seyfer**
no breaking changes. shall work?

### CODE REVIEW

**Comment by B-PRAVEEN** [comment]
$widescreen-enabled :false (need to set if want the same look and margin).

**Comment by B-PRAVEEN** [comment]
I have angular 6 Version, Shall I pull into a new branch?

**Comment by cssninjaStudio** [comment]
For Angular 6 version, we need a separate branch.

**Comment by cssninjaStudio** [comment]
@seyfer please set the widescreen variable to false and base font size to 14px instead of 16px before I can merge this PR.

**Pull request closed without merging**
